### ISSUE TITLE
Add Playwright E2E Testing for Frontend Site

### ISSUE THREAD

**Issue by runewake2** [Letterbook/Letterbook#205]
# Purpose

We're introducing a Letterbook frontend built using Razor pages starting with #204. We need a way to test the functionality we're introducing in this frontend and validate its features as the project grows.

One of the ways we can do that is through the introduction of end to end (E2E) testing. Playwright is one of a few options for this with built-in support for .NET that can provide a way for us to build and run e2e tests against a variety of web browsers automatically as part of a PR's validation.

E2E testing is needed to ensure Letterbook functionality and behavior as exposed to users continues to operate in a stable, predictable and reliable way.

## Steps

- [ ] #206 Introduce a new Playwright based e2e test project
- [ ] Execute Playwright tests as part of PR's when a web or playwright test project change is detected in the PR (depending on how our dependency structure looks we may want to execute these tests regardless of the project that is changed)

## Related

- #196

**Comment by jenniferplusplus** [comment]
I'm actually fine with running integration tests on every change. I'm a lot less protective of github action's time than I am of contributors.
