### ISSUE TITLE
tempo service fails on creation with missing permission

### ISSUE THREAD

**Issue by gianlucaschoefer** [Letterbook/Letterbook#284]
**Describe the bug**
Bringing up the docker compose locally fails after a few seconds when tempo tries to create a store at `/tmp/tempo/blocks` with the exception: `2024-07-16 16:36:59 level=error ts=2024-07-16T14:36:59.350614294Z caller=main.go:121 msg="error running Tempo" err="failed to init module services: error initialising module: store: failed to create store: mkdir /tmp/tempo/blocks: permission denied"`. 

**Expected behavior**
The store can be created and the container starts up normally.

**Additional context**
- once the directory exists the this problem doesn't arise anymore
- looks like [a similar issue has been observed when deploying tempo with OpenShift, including a proposed workaround of mounting `/tmp` directly](https://github.com/grafana/tempo/issues/1657#issuecomment-2049987178), which worked for me

Docker Version info:
```
Client:
 Version:           27.0.3
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7d4bcd8
 Built:             Fri Jun 28 23:59:41 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.32.0 (157355)
 Engine:
  Version:          27.0.3
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       662f78c
  Built:            Sat Jun 29 00:02:44 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.18
  GitCommit:        ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc:
  Version:          1.7.18
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by jenniferplusplus** [comment]
@gianlucaschoefer thanks for reporting this. I just noticed it myself a couple of days ago. I think the fix is already in main. Can you pull again and check for that? If it's still happening I'll be sure to get it merged soon.

**Comment by jenniferplusplus** [comment]
Sorry, it looks like that fix was only on a branch. I cherry picked it to main in #287, in case you'd like to have a look

**Comment by gianlucaschoefer** [comment]
I just pulled and tried it out. Works great, thank you for letting me know :)
