### ISSUE TITLE
API Authorization

### ISSUE THREAD

**Issue by jenniferplusplus** [Letterbook/Letterbook#36]
We need an authorization framework. A lot of authz can be handled at the api layer. We have a JWT based authentication mechanism already. We would preferably use that to implement OIDC. That's not trivial, but openiddict is a relatively known quantity. From there we can implement a claims based framework. 

But wait there's more!

First, we don't have a set of claims defined for ourselves, much less any kind of hierarchy or organization. We need that, but it can probably wait a little while.

Second, I had been thinking we need to also support mastodon style claims, but maybe we don't? Apps will most likely request them, but we can provide whatever claim we want in response to that. It would be good to confirm either way.

Third, we definitely need to support http signature headers as a combined server to server authn/authz mechanism. It is what it is.

So! To do:

- [x] setup policy based authz, or any other scheme that makes it easy to mix and match our methods.
- [x] share whatever you learn about claims and any thing else that's relevant
- [x] #223
- [x] HttpSignatures authentication scheme
[This article may help](https://matteosonoio.it/aspnet-core-authentication-schemes/)
[Or the aspnet security guide](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/?view=aspnetcore-8.0)
- [x] ~~implement oidc with openiddict~~ (punting to the future, this is actually a major effort)

**Comment by rytmis** [comment]
I'm interested in participating in this project, and this seems like something I might be able to help with. 

I don't know OpenIddict aside from what I've read from their docs, but I've shipped a number of IdentityServer deployments and worked with various oidc implementations. Not an expert by any means, but not completely lost either. And I at least think I have some sort of handle on the aspnetcore authn parts.

**Comment by jenniferplusplus** [comment]
@rytmis that's great, I'd love to have some help with this! Of course, it's a big topic. I don't want to just throw you into the deep end with it. I've been giving authz some thought at a high level lately, and lot of that is captured in the[ draft ADR doc that's open for review](https://github.com/Letterbook/Letterbook/pull/183). Definitely have a look at that, I'd like to know your thoughts.

My sense is that OIDC is not urgent, but I also want to minimize how much trouble it is to integrate later. So I would also really like to have some thoughts on whether than can be delayed or not.

**Comment by jenniferplusplus** [comment]
Of course, I also image you'd like to get started working on something concrete. I think setting up authz policy classes is likely a good first step. I want to have the fist party API, mastodon API, and activitypub/http signatures share the same core authorization logic and flows. So, we likely need at least 2 policies: JWT and http signatures. Which makes this at least moderately complicated.

**Comment by rytmis** [comment]
I don't think OIDC is urgent if we're not looking at interactive client apps yet, and it'll also require at least some user interface elements for login and consent as part of the authorization flow, so it might well make sense to delay that.

I don't have a good handle on the ActivityPub concepts yet, so I think I'll have to do some reading before I can form an informed opinion on the logical side of authorization in a federated scenario (e.g. which actor can perform actions on which entity and how that should be represented in the implementation).

Do you already have something in mind for how the authnz infrastructure should be set up, other than the general design principles? I can see there's the authorization service introduced in https://github.com/Letterbook/Letterbook/pull/168, so I expect you already have some notion of how it fits in the picture?

**Comment by jenniferplusplus** [comment]
Honestly, no, all I really have is the general design principles.

For authorizing activitypub activities, the details can wait. It would be really helpful to even have an empty framework we can build from. My general thinking is that some authz middleware will need to do a couple things

1. validate inbound http message signatures. (it's fine to put off how that happens until later)
2. construct a claims principle for the request, notably including the origin as the claims issuer.

This middleware needs to also play nicely with a more typical JWT bearer middleware.

And then the full authz decision takes the issuer into account, and decides whether or not it has the authority to grant the claims it's making. In addition to whether the claims are adequate, of course.

**Comment by jenniferplusplus** [comment]
Side note, re: http signatures

We have a workable solution for signing messages, and it has all the parts we would need to build a validator. It's built on top of the https://github.com/Unisys/NSign project, but I had to modify it to support using keys that are only known at runtime.

I intend to extract this out to a dedicated library, but it hasn't been a priority. As you're working, I would plan for that. It will probably utilize dependency injection to retrieve some `SigningKeyProvider` and `VerificationKeyProvider` objects, and then use those to sign and verify, respectively.

**Comment by jenniferplusplus** [comment]
small note: I updated the order of the todo list to reflect what seems to be the best way to get started

**Comment by jenniferplusplus** [comment]
I think you're right on all counts. I don't anticipate that the instance actor will require special handling, but it's a scenario that does happen. And it's good to know that the actor type is something other than Person.

As far as enriching the (ActivityPub) endpoints, that's usually not possible. We can do it with GET requests, but everything else comes in through the inbox, and the POST body is the only source of information about the message. The Mastodon API also doesn't do much of that. They mostly depend on the authz token for everything.

Letterbook's first-party API does/will. This is the general pattern I'm going for with the letterbook API:
https://hachyderm.io/@jenniferplusplus/112132252735855594

I should have that work ready for PR soon, but currently it's just in a branch: https://github.com/Letterbook/Letterbook/blob/enhancement/post-api/Letterbook.Api/Controllers/PostsController.cs

**Comment by jenniferplusplus** [comment]
@rytmis it's been a few days, so I just want to check in and see if you need anything from me. If you like, we have a small discord for contributors, I can send you an invite. It helps to have real time chat when talking about complex topics.

**Comment by rytmis** [comment]
That sounds great, I've had some thoughts that didn't quite feel well-formed enough for this thread.

I'm rytmis@hachyderm.io on Fedi, if you want to DM the invite there.

**Comment by jenniferplusplus** [comment]
I went ahead and assigned this to you, just to make it more visible what's in progress

**Comment by jenniferplusplus** [comment]
I think the remaining authn work for near future is captured in #212, so we can call this one done.
