### ISSUE TITLE
Webfinger API

### ISSUE THREAD

**Issue by jenniferplusplus** [Letterbook/Letterbook#79]
- [ ] API endpoints (partially implemented in #87)
- [x] At least enough core profile logic to support doing profile lookups (see #34)
- [ ] Webfinger client for doing our own lookups

**Comment by jenniferplusplus** [comment]
Partially done in #87 (commenting to get the issues to link to each other)

**Comment by magicalunicor** [comment]
hi! I'll try start this today, see what I can come up with :)

**Comment by jenniferplusplus** [comment]
That would be awesome, thank you!

If you're starting on the API, that lives here: https://github.com/Letterbook/Letterbook/blob/main/Letterbook.Api/Controllers/WebFingerController.cs#L17-L24

That calls the webfinger DTO constructor directly, but I think it would be more maintainable to write an automapper from Profile -> webfinger DTO, and use that instead. The Profile service is built out enough now that you can probably get all you need from that. That method is using the Account service because it was the only one that existed at the time. But that definitely won't be the right one.

If you're working on a webfinger client, we should talk, because that will intersect somewhat with #102 which I'm trying to get finished up this week. Please do reach out if you have questions or anything.

**Comment by jenniferplusplus** [comment]
Hi @magicalunicor!

I want to check in and see how things are coming along for you. Have you had a chance to start? Are you stuck on anything? Can I provide any guidance?

I just want to make sure you have what you need, not trying to add any pressure 😃 

I have a lot of time for this today and tomorrow, so if a chat would help, this is a good time for it.

**Comment by magicalunicor** [comment]
hey @jenniferplusplus ! Thanks for checking in.
Sadly I haven't started yet... work, life and sleep got in the way haha.
If I find any trouble i'll let you know though

**Comment by jenniferplusplus** [comment]
Hi, @magicalunicor, checking in again! We're going to need webfinger APIs in the near future. If you've started working on it, that's great, and I'm happy to help. If not, I'll pull it back into the to do column.
